name: twin-client-js

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:

      - name: Use Node.JS 22.x
        uses: actions/setup-node@v2
        with:
          node-version: 22.x

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        working-directory: twin-client-js
        run: npm run deps

      - name: Test
        working-directory: twin-client-js
        run: npm run test-ci
